config/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("broadcasts/", include("broadcasts.urls", namespace="broadcasts")),
    path("studios/", include("studios.urls", namespace="studios")),
    path("accounts/", include("allauth.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update_profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update_password/", views.UpdatePassword.as_view(), name="password"),
]

templates/partials/footer.html
<div class="container mx-auto w-4/5 flex flex-row pt-16 pb-8">
    <div class="grid grid-span-4 mr-32">
        <h5 class="footer-item">BUSKER</h5>
        <ul>
            <li class="footer-link">(주)버스커</li>
            <li class="footer-link">사업자등록번호 000-00-00000</li>
            <li class="footer-link">법인등록번호 000000-0000000</li>
            <li class="footer-link">대표 버스커</li>
            <li class="footer-link">서울특별시 종로구 홍지동 홍지문2길 20</li>
            <li class="footer-link">contact@busker.com</li>
            <li class="footer-link">000-0000-0000</li>
            <span class="footer-link flex justify-center mt-32">&copy; 2021 BUSKER. All rights reserved.</span>
        </ul>
    </div>

    <div class="grid grid-span-2 mr-32">
        <ul>
            <h5 class="footer-item text-sm">서비스 소개</h5>
            <li class="footer-link"><a href="#">Resource</a></li>
            <li class="footer-link"><a href="#">Resource name</a></li>
            <li class="footer-link"><a href="#">Another resource</a></li>
            <li class="footer-link"><a href="#">Final resource</a></li>
        </ul>
    </div>

    <div class="gird grid-span-2 mr-32">
        <h5 class="footer-item text-sm">서비스 정책</h5>
        <ul>
            <li class="footer-link"><a href="#">main</a></li>
            <li class="footer-link"><a href="#">Question</a></li>
            <li class="footer-link"><a href="#">Service usage guide</a></li>
            <li class="footer-link"><a href="#">Contact us</a></li>
        </ul>
    </div>

    <div class="gird grid-span-2 mr-32"></div>
</div>

templates/partials/nav.html
<ul class="flex items-center justify-center h-full">
    {% if user.is_authenticated %}
        <li class="nav-link">
<<<<<<< HEAD
            {{user.username}}
=======
            {% if user.nickname %}
                {{user.nickname}}
            {% else %}
                <a href="{% url 'users:update' %}">닉네임 설정하기</a>
            {% endif %}
>>>>>>> f4988b5309290f577d9ed38fe86ee91a1c8c4298
            {% if user.busker %}
                <i class="fas fa-microphone text-yellow-400 ml-1"></i>
            {% endif %}
        </li>
        <li class="nav-link">
            <a href="{% url 'users:profile' user.pk %}">마이페이지</a>
        </li>
        
        <li class="nav-link">
            <a href="{% url 'users:logout' %}">Logout</a>
        </li>
    {% else %}
        <li class="nav-link">
            <a href="{% url 'users:login' %}">Login</a>
        </li>
        <li class="nav-link">
            <a href="{% url 'users:signup' %}">Join</a>
        </li>
    {% endif %}
</ul>

templates/partials/social_login.html
{% load socialaccount %}
{% providers_media_js %}

<section class="flex flex-col items-center justify-center space-y-4 mb-20">
    <div>
        <ul class="mt-5 flex items-center justify-around space-x-5">
            <a href="{% provider_login_url 'google' %}"> 
                <li class="shadow w-10 h-10 rounded flex items-center justify-center text-blue-700 hover:bg-blue-700 hover:text-white bg-center bg-cover" style="background-image: url(https://blog.kakaocdn.net/dn/eKBsMH/btqPgGk7Fxx/Ro2eTSkL0h0YzcFdHEejl0/img.png);">
                </li>
            </a>

            <a href="{% provider_login_url 'naver' %}"> 
                <li class="shadow w-10 h-10 rounded flex items-center justify-center text-blue-700 hover:bg-blue-700 hover:text-white bg-cover bg-center" style="background-image: url(https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2F20160504_295%2Fzzlidde_1462360339348GT0M2_PNG%2F2016-05-04_20.11.40.png);">
                </li>
            </a>

            <a href="{% provider_login_url 'kakao' %}"> 
                <li class="shadow w-10 h-10 rounded flex items-center justify-center text-blue-700 hover:bg-blue-700 hover:text-white bg-cover bg-center" style="background-image: url(https://upload.wikimedia.org/wikipedia/commons/f/f2/Kakao_logo.jpg);">
                </li>
            </a>
         
        </ul>
    </div>
</section>