broadcasts/urls.py
from django.urls import path
from . import views

app_name = "broadcasts"

urlpatterns = [
    path("", views.home, name="home"),
    path("main", views.main_view, name="main"),
    path("create/", views.CreateBroadcastView.as_view(), name="create"),
    path("<int:pk>/", views.BroadcastDetail.as_view(), name="detail"),
    path("update/<int:pk>/", views.UpdateBroadcastView.as_view(), name="update"),
    path("delete/<int:pk>/", views.DeleteBroadcastView.as_view(), name="delete"),
]

config/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("broadcasts/", include("broadcasts.urls", namespace="broadcasts")),
    path("studios/", include("studios.urls", namespace="studios")),
    path("accounts/", include("allauth.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studios/urls.py
from django.urls import path
from . import views


app_name = "studios"

urlpatterns = [
    path("create/", views.CreateStudioView.as_view(), name="create"),
    path("<int:pk>/", views.DetailStudioView.as_view(), name="detail"),
    path("update/<int:pk>/", views.UpdateStudioView.as_view(), name="update"),
    path("delete/<int:pk>/", views.DeleteStudioView.as_view(), name="delete"),
    path("<int:pk>/posts/", views.StudioPostsView, name="posts"),
    path(
        "<int:pk>/posts/add",
        views.AddPostView.as_view(),
        name="add-posts",
    ),
    path(
        "<int:studio_pk>/posts/<int:pk>/",
        views.DetailPostView.as_view(),
        name="post-detail",
    ),
    path(
        "<int:studio_pk>/posts/<int:pk>/update",
        views.UpdatePostView.as_view(),
        name="post-update",
    ),
    path(
        "<int:studio_pk>/posts/<int:pk>/delete",
        views.DeletePostView.as_view(),
        name="post-delete",
    ),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update_profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update_password/", views.UpdatePassword.as_view(), name="password"),
]

broadcasts/models.py
from django.db import models
from django.urls import reverse
from core import models as core_models
from users import models as user_models
from django_countries.fields import CountryField
import random
from random import randint
from django.db.models import Max


class AbstractItem(core_models.TimeStampedModel):

    """Abstract Item Model Definition"""

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class PictureQuality(AbstractItem):

    """Picture Quality Model Definition"""

    pass

    class Meta:
        verbose_name = "Picture Quality"


class Genre(core_models.TimeStampedModel):

    """Genre Model Definition"""

    name = models.CharField(max_length=80)

    class Meta:
        verbose_name = "Genre"

    def __str__(self):
        return self.name


class Broadcast(core_models.TimeStampedModel):

    """Broadcast Model Definition"""

    name = models.CharField(max_length=120, blank=True, null=True)
    desc = models.TextField(blank=True, null=True)
    image = models.ImageField(
        upload_to="broadcast_images",
        blank=True,
        null=True,
    )
    on_air = models.BooleanField(default=False)
    country = CountryField(blank_label="(select country)", default="KR")
    genres = models.ManyToManyField("Genre", blank=True)
    picture_quality = models.ForeignKey(
        "PictureQuality",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    host = models.OneToOneField(
        user_models.User,
        related_name="broadcast",
        on_delete=models.CASCADE,
        primary_key=True,
    )

    def get_absolute_url(self):
        return reverse("broadcasts:detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.name

    def get_on_airs(self):
        on_airs = Broadcast.objects.filter(on_air=True)
        return on_airs

broadcasts/forms.py
from django import forms
from django.forms import models
from . import models
from django_countries.fields import CountryField


class CreateBroadcastForm(forms.ModelForm):
    class Meta:
        model = models.Broadcast
        fields = (
            "name",
            "desc",
            "image",
            "on_air",
            "genres",
            "picture_quality",
        )

    name = forms.CharField(label="채널 이름")
    desc = forms.CharField(label="채널 설명")

    def save(self, *args, **kwargs):
        broadcast = super().save(commit=False)
        return broadcast


class UpdateBroadcastForm(forms.Form):
    pass

broadcasts/views.py
from django.http import request
from django.shortcuts import redirect, render
from django.urls import reverse
from django.urls.base import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, FormView
from django.http import Http404
from django.views.generic.edit import DeleteView
from . import models, forms
import broadcasts
import random


def home(request):
    broadcasts = models.Broadcast.objects.filter(on_air=True)
    random_on_air = models.Broadcast.objects.filter(on_air=True).order_by("?").first()
    return render(
        request,
        "broadcasts/home.html",
        {
            "broadcasts": broadcasts,
            "random_on_air": random_on_air,
        },
    )


def main_view(request):
    context = {}
    return render(request, "broadcasts/main.html", context=context)


class DeleteBroadcastView(DeleteView):

    model = models.Broadcast
    template_name = "broadcasts/broadcast_confirm_delete.html"
    success_url = reverse_lazy("core:home")


class BroadcastDetail(DetailView):

    model = models.Broadcast
    template_name = "broadcasts/broadcast_detail.html"
    context_object_name = "broadcast"

    def get_queryset(self):
        broadcasts = models.Broadcast.objects.all()
        return broadcasts


class CreateBroadcastView(FormView):

    template_name = "broadcasts/broadcast_create.html"
    form_class = forms.CreateBroadcastForm

    def form_valid(self, form):
        broadcast = form.save()
        broadcast.host = self.request.user
        broadcast.save()
        form.save_m2m()
        return redirect(reverse("broadcasts:detail", kwargs={"pk": broadcast.pk}))


class UpdateBroadcastView(UpdateView):

    model = models.Broadcast
    template_name = "broadcasts/broadcast_update.html"
    fields = (
        "name",
        "desc",
        "image",
        "on_air",
        "country",
        "genres",
        "picture_quality",
    )

    def get_object(self, queryset=None):
        broadcast = super().get_object(queryset=queryset)
        if broadcast.host.pk != self.request.user.pk:
            raise Http404()
        else:
            return broadcast

templates/broadcasts/broadcast_confirm_delete.html
{% extends "base.html" %}

{% block page_title %}방송채널 삭제하기{% endblock page_title %}

{% block content %}
<div class="container w-4/5 mt-16 mb-40 mx-auto h-75vh">
    <form method="post" class=" bg-white w-full h-25vh p-12 rounded-md text-black">
        {% csrf_token %}
        <p class="text-xl mb-8 w-full">경고❗️ 정말로 "{{ object }}" 채널을 삭제하시겠습니까?? 삭제하기 버튼을 누를 시, 해당 채널에 관련된 모든 데이터가 삭제됩니다.</p>
        <input type="submit" value="삭제" class="block w-64 absolute bg-red-500 text-white border-none cursor-pointer">
    </form>
</div>

{% endblock %}

templates/broadcasts/broadcast_create.html
{% extends "base.html" %}

{% block page_title %}채널 생성하기{% endblock page_title %}

{% block content %}
<div class="container w-4/5 mt-16 mb-40 mx-auto">
    <div class="w-4/5 mx-auto">
        <h1 class="font-bold text-2xl mb-10">방송 채널 생성</h1>
        <form action="{% url 'broadcasts:create' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn w-full">방송 채널 만들기</button>
        </form>
    </div>
</div>
    
{% endblock %}

templates/broadcasts/broadcast_detail.html
{% extends "base.html" %}

{% block page_title %}{{broadcast.name}}{% endblock page_title %}

{% block content %}

<div class="container w-4/5 mx-auto mb-25vh">
    <div class="flex flex-row mt-12 mb-8">
        <div class="relative w-3/4 h-75vh rounded-md bg-gray-900 flex flex-col justify-center items-center">
            <i class="fas fa-play text-7xl mb-10 hover:opacity-70"></i>
            <span class="absolute top-5 left-5 z-40 text-gray-300">실시간 방송 및 채팅 기능 개발 중입니다</span>
            <span class="absolute top-5 right-5 z-40 text-yellow-400 font-bold text-lg">BUSKER</span>
            <span class="absolute bottom-2 right-2 text-gray-300 text-sm">{{broadcast.picture_quality}}</span>
        </div>
        <div class="w-1/4 h-75vh bg-gray-100 ml-4 rounded-md flex flex-col relative">
            <textarea class="resize-none border h-5/6 rounded-md"></textarea> 
            <input type="text ring-gray-300" name="chat" placeholder="채팅 메세지를 입력해주세요" id="id_chat" class="w-11/12 mx-1 absolute bottom-11 right-2">
            <div class="absolute bottom-3 right-2">
                <button class="bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-1 px-5 rounded ">SEND</button>
            </div>
        </div>    
    </div>
    <div>
        <div class="flex justify-between mb-1">
            <span class="w-3/4 font-bold text-3xl text-yellow-400 block truncate">{{broadcast.name}}</span>
            <div>
                {% if broadcast.host == user %}
                    <a href="{% url 'broadcasts:update' pk=broadcast.pk %}" class="btn bg-yellow-400 rounded-full px-3 text-sm ml-3">내 채널 수정하기</a>
                {% endif %}
                {% if broadcast.host.studio %}
                    <a href="{% url 'studios:posts' broadcast.host.studio.pk %}"><span class="btn bg-yellow-400 rounded-full px-3 text-sm ml-3">스튜디오 가기</span></a>
                {% endif %}
            </div>
        </div>
        <div class="border-b border-gray-400 pb-3 mb-32">
            <div class="flex items-center mb-3">
                <span class="font-semibold text-lg">{{broadcast.host.nickname}}</span>
                <div class="border-r h-4 border-white ml-3"></div>
                <span>
                    {% for g in broadcast.genres.all %}                                
                        <span class="text-lg ml-3">{{g}}</span>                                                                         
                    {% endfor %}
                </span>
                <div class="border-r h-4 border-white ml-3"></div>
                {% if broadcast.on_air %}
                    <span class="text-sm ml-3 bg-blue-300 text-busker-navy px-2 rounded-full">On Air</span>                                                                         
                {% endif %}
            </div>
            <span class="text-lg">{{broadcast.desc}}</span>
        </div>
        
        <div class="flex flex-row flex-wrap mb-24">
            {% for on_air in broadcast.get_on_airs.all %}
                <div class="w-1/5 pb-2 px-2">
                    <a href="{% url 'broadcasts:detail' on_air.pk %}">
                        {% if on_air.image %}
                            <div class="w-full h-56 rounded-3xl mb-2 bg-gray-100 bg-cover bg-center" style="background-image: url({{on_air.image.url}});">
                                <div class="w-full h-56 rounded-3xl bg-black bg-opacity-40 flex items-end px-3 pb-3">
                                    <div class="w-full flex flex-col z-10">
                                        <span class="text-lg mb-px overflow-hidden text-yellow-400 font-semibold block truncate">{{ on_air.name }}</span>
                                        <div class="flex justify-between items-center">
                                            <span class="text-xs mb-px">{{on_air.host.nickname}}</span>
                                            <div class="m-0 p-0 flex items-center">
                                            {% for g in on_air.genres.all %}                           
                                                <span class="text-xs mb-px ml-2">{{g}}</span>                                                                         
                                            {% endfor %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <div class="w-full h-56 rounded-3xl mb-2 bg-gray-900 bg-cover bg-center">
                                <div class="w-full h-56 rounded-3xl bg-black bg-opacity-40 flex items-end px-3 pb-3 relative">
                                    <div class="w-full flex flex-col z-10">
                                        <span class="text-lg font-bold text-yellow-400 absolute top-20 left-20">BUSKER</span>
                                        <span class="text-lg mb-px overflow-hidden text-yellow-400 font-semibold block truncate">{{ on_air.name }}</span>
                                        <div class="flex justify-between items-center">
                                            <span class="text-xs mb-px">{{on_air.host.nickname}}</span>
                                            <div class="m-0 p-0 flex items-center">
                                            {% for g in on_air.genres.all %}                           
                                                <span class="text-xs mb-px ml-2">{{g}}</span>                                                                         
                                            {% endfor %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}    
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/broadcasts/broadcast_update.html
{% extends "base.html" %}

{% block page_title %}채널 수정 및 삭제{% endblock page_title %}

{% block content %}

<div class="container w-4/5 mt-16 mb-64 mx-auto">
    <div class="w-4/5 mx-auto">
        <h1 class="font-bold text-2xl mb-10 text-yellow-400">방송 채널 수정 및 삭제</h1>
        <form action="{% url 'broadcasts:update' broadcast.pk %}" method="POST" enctype="multipart/form-data" class="mb-5">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn w-full mt-10">수정하기</button>
        </form>
        <a href="{% url 'broadcasts:delete' broadcast.pk %}" class="text-center block btn bg-red-500 text-gray-100">삭제하기</a>
    </div>
</div>

{% endblock %}

templates/broadcasts/detail.html
{% extends "base.html" %}

{% block page_title %}{{broadcast.name}}{% endblock page_title %}

{% block content %}

<h1>Video</h1>
<h1>CHAT</h1>

<span>{{broadcast.desc}}</span>
<span>
    {{broadcast.name}} | {{broadcast.broadcast_host}}
</span>

{% endblock %}

templates/broadcasts/home.html
{% extends "base.html" %}

{% block page_title %}Home{% endblock page_title %}

{% block content %}

<div class="container w-4/5 mx-auto">
    <div class="w-full h-75vh rounded-md bg-busker-navy mt-12 bg-cover bg-center flex flex-col justify-center items-center mb-36" style="background-image: url(https://images.unsplash.com/photo-1453090927415-5f45085b65c0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&);">
        <div>
            {% if broadcasts %}
                <h1 class="text-white font-bold text-5xl mb-16">Anyone Can Sing, Anywhere</h1>
                <a href="{% url 'broadcasts:detail' pk=random_on_air.pk %}" class="flex flex-col justify-center items-center">
                    <i class="fas fa-play text-7xl mb-10 hover:opacity-70"></i>
                    <span class="text-white text-3xl">START RANDOM LIVE</span>
                </a>
            {% else %}
                <h1 class="text-white font-bold text-5xl mb-16">Anyone Can Sing, Anywhere</h1>
                <a href="#" class="flex flex-col justify-center items-center">
                    <i class="fas fa-play text-7xl mb-10 hover:opacity-70"></i>
                    <span class="text-white text-3xl">START RANDOM LIVE</span>
                </a>
            {% endif %}
        </div>
    </div> 

    <div class="flex justify-center mb-16">
        <span class="text-2xl border-b-2 py-2 font-bold">On Air List</span>
    </div>
    
    <div class="flex flex-row flex-wrap mb-64">
        {% for broadcast in broadcasts %}
            {% if broadcast.on_air == True %}
            <div class="w-1/4 pb-2 px-2">
                <a href="{% url 'broadcasts:detail' pk=broadcast.pk %}">
                    {% if broadcast.image %}
                    <div class="w-full h-64 rounded-3xl mb-2 bg-gray-900 bg-cover bg-center" style="background-image: url({{broadcast.image.url}});">
                        <div class="w-full h-64 rounded-3xl bg-black bg-opacity-40 flex items-end px-3 pb-3">
                            <div class="w-full flex flex-col">
                                <span class="text-lg mb-px font-semibold text-yellow-400 block truncate">{{broadcast.name}}</span>
                                <div class="flex justify-between items-center">
                                    <span class="text-xs mb-px">{{broadcast.host.nickname}}</span>
                                    <div class="flex items-center">
                                    {% for g in broadcast.genres.all %}                                
                                        <span class="text-xs mb-px ml-2">{{g}}</span>                                                                         
                                    {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% else %}
                    <div class="w-full h-64 rounded-3xl mb-2 bg-gray-900 bg-cover bg-center">
                        <div class="w-full h-64 rounded-3xl bg-black bg-opacity-40 flex items-end px-3 pb-3 relative">
                            <div class="w-full flex flex-col">
                                <span class="text-3xl font-bold text-yellow-400 absolute top-20 left-24">BUSKER</span>
                                <span class="text-lg mb-px font-semibold text-yellow-400 block truncate">{{broadcast.name}}</span>
                                <div class="flex justify-between items-center">
                                    <span class="text-xs mb-px">{{broadcast.host.nickname}}</span>
                                    <div class="flex items-center">
                                    {% for g in broadcast.genres.all %}                                
                                        <span class="text-xs mb-px ml-2">{{g}}</span>                                                                         
                                    {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </a>
            </div>
            {% endif %}
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/broadcasts/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">
</head>
<body>
<h3 id="label-username">USERNAME</h3>
<div>
    <input type="text" id="username">
    <button id="btn-join">Join Room</button>
</div>

<div class="main-grid-container">
    <div id="video-container">
        <div>
            <video id="local-video" style="float: left;" autoplay playsinline></video>
            <button id="btn-toggle-audio">Audio Mute</button>
            <button id="btn-toggle-video">Video Off</button>
        </div>
        <div id="chat">
            <h3>CHAT</h3>
            <div id="messages">
                <ul id="message-list"></ul>
            </div>

            <div>
                <textarea id="chat-log" cols="90" rows="20"></textarea><br/>
                <input id="msg" type="text" size="100">
                <input id="btn-send-msg"type="button" value="Send Message"/>
                <button id="btn-share-screen">Share Screen</button>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
<script>
    var chatSocket = new WebSocket( 'ws://' +window.location.host + '/broadcasts/main' );

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        document.querySelector('#chat-log').value += (message + '\n');
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#msg').focus();
    document.querySelector('#msg').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#btn-send-msg').click();
        }
    };

    document.querySelector('#btn-send-msg').onclick = function(e) {
        var messageInputDom = document.querySelector('#msg');
        var message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message
        }));

        messageInputDom.value = '';
    };
</script>

</body>
</html>