config/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("broadcasts/", include("broadcasts.urls", namespace="broadcasts")),
    path("studios/", include("studios.urls", namespace="studios")),
    path("accounts/", include("allauth.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studios/urls.py
from django.urls import path
from . import views


app_name = "studios"

urlpatterns = [
    path("create/", views.CreateStudioView.as_view(), name="create"),
    path("<int:pk>/", views.DetailStudioView.as_view(), name="detail"),
    path("update/<int:pk>/", views.UpdateStudioView.as_view(), name="update"),
    path("delete/<int:pk>/", views.DeleteStudioView.as_view(), name="delete"),
    path("<int:pk>/posts/", views.StudioPostsView, name="posts"),
    path(
        "<int:pk>/posts/add",
        views.AddPostView.as_view(),
        name="add-posts",
    ),
    path(
        "<int:studio_pk>/posts/<int:pk>/",
        views.DetailPostView.as_view(),
        name="post-detail",
    ),
    path(
        "<int:studio_pk>/posts/<int:pk>/update",
        views.UpdatePostView.as_view(),
        name="post-update",
    ),
    path(
        "<int:studio_pk>/posts/<int:pk>/delete",
        views.DeletePostView.as_view(),
        name="post-delete",
    ),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update_profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update_password/", views.UpdatePassword.as_view(), name="password"),
]

studios/models.py
from typing import Tuple
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from core import models as core_models
import core
from users import models as user_models


class Category(core_models.TimeStampedModel):

    """Category Model Definition"""

    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Post(core_models.TimeStampedModel):

    """Post Model Definition"""

    class Meta:
        ordering = ["-created"]

    NOTICE = "NT"
    BULLETIN = "BL"
    BOARD_CHOICES = [
        (NOTICE, "공지사항"),
        (BULLETIN, "자유게시판"),
    ]

    title = models.CharField(max_length=200, null=True)
    writer = models.ForeignKey(
        user_models.User, related_name="posts", on_delete=models.CASCADE
    )
    body = RichTextUploadingField(null=True)
    studio = models.ForeignKey("Studio", related_name="posts", on_delete=models.CASCADE)
    category = models.CharField(
        max_length=40, null=True, choices=BOARD_CHOICES, default=BULLETIN
    )

    def __str__(self):
        return self.title[:30]


class Studio(core_models.TimeStampedModel):

    """Studio Model Definition"""

    name = models.CharField(max_length=160, blank=True, null=True)
    desc = models.TextField(blank=True, null=True)
    image = models.ImageField(
        upload_to="studio_images",
        blank=True,
        null=True,
        default="broadcast_images/no_image.png",
    )
    host = models.OneToOneField(
        user_models.User,
        related_name="studio",
        on_delete=models.CASCADE,
        primary_key=True,
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("studios:detail", kwargs={"pk": self.pk})

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls.base import reverse


class User(AbstractUser):

    """Custom User Model"""

    GENDER_MALE = "male"
    GENDER_FEMALE = "female"
    GENDER_OTHER = "other"
    GENDER_CHOICES = [
        (GENDER_MALE, "male"),
        (GENDER_FEMALE, "female"),
        (GENDER_OTHER, "other"),
    ]

    LANGUAGE_KOREAN = "KR"
    LANGUAGE_ENGLISH = "EN"
    LANGUAGE_CHOICES = [
        (LANGUAGE_KOREAN, "Korean"),
        (LANGUAGE_ENGLISH, "English"),
    ]

    CURRENCY_KRW = "KRW"
    CURRENCY_USD = "USD"
    CURRENCY_CHOICES = [(CURRENCY_KRW, "KRW"), (CURRENCY_USD, "USD")]

    LOGIN_EMAIL = "email"
    LOGIN_KAKAO = "kakao"
    LOGIN_CHOICES = [
        (LOGIN_EMAIL, "Email"),
        (LOGIN_KAKAO, "Kakao"),
    ]

    avatar = models.ImageField(upload_to="avatars", blank=True)
    nickname = models.CharField(max_length=120, blank=True, null=True)
    bio = models.TextField(blank=True, null=True, default="소개를 입력해주세요!")
    gender = models.CharField(
        max_length=20, choices=GENDER_CHOICES, blank=True, null=True
    )
    birthdate = models.DateField(blank=True, null=True)
    phone = models.CharField(max_length=30, blank=True, null=True)
    language = models.CharField(
        max_length=2, choices=LANGUAGE_CHOICES, blank=True, null=True
    )
    currency = models.CharField(
        max_length=3, choices=CURRENCY_CHOICES, blank=True, null=True
    )
    busker = models.BooleanField(null=True)
    login_method = models.CharField(
        max_length=20, choices=LOGIN_CHOICES, default=LOGIN_EMAIL
    )

    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})

studios/forms.py
from django import forms
from django.forms import fields, widgets
from . import models


class CreatePostForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = (
            "title",
            "body",
        )

    def save(self, pk, user, *args, **kwargs):
        post = super().save(commit=False)
        studio = models.Studio.objects.get(pk=pk)
        post.studio = studio
        post.writer = user
        post.save()


class CreateStudioForm(forms.ModelForm):
    class Meta:
        model = models.Studio
        fields = (
            "name",
            "desc",
            "image",
        )

    def save(self, *args, **kwargs):
        studio = super().save(commit=False)
        return studio


class UpdateStudioForm(forms.Form):
    pass

users/forms.py
from django import forms
from django.db.models import fields
from django.forms import ModelForm
from django.forms import models
from django.forms.widgets import PasswordInput
from . import models


class LoginForm(forms.Form):

    email = forms.EmailField(label="이메일")
    password = forms.CharField(widget=forms.PasswordInput, label="패스워드")

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("패스워드를 확인해주세요."))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("해당 유저가 존재하지 않습니다."))


class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = [
            "email",
            "nickname",
            "first_name",
            "last_name",
            "busker",
        ]

    email = forms.EmailField(label="이메일")
    nickname = forms.CharField(label="닉네임")
    first_name = forms.CharField(label="이름")
    last_name = forms.CharField(label="성")
    password = forms.CharField(widget=PasswordInput, label="패스워드")
    password1 = forms.CharField(widget=PasswordInput, label="패스워드 확인")
    busker = forms.BooleanField(label="버스커(가수)입니까?")

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError("User already exists with that email.")
        except models.User.DoesNotExist:
            return email

    def clean_nickname(self):
        nickname = self.cleaned_data.get("nickname")
        try:
            models.User.objects.get(nickname=nickname)
            raise forms.ValidationError("User already exists with that nickname.")
        except models.User.DoesNotExist:
            return nickname

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")
        if password != password1:
            raise forms.ValidationError("Password confirmation does not match")
        else:
            return password

    def save(self):
        user = super().save(commit=False)
        email = self.cleaned_data.get("email")
        nickname = self.cleaned_data.get("nickname")
        password = self.cleaned_data.get("password")
        user.username = email
        user.nickname = nickname
        user.set_password(password)
        user.save()

studios/views.py
from django.forms import forms
from django.shortcuts import redirect, render
from django.urls import reverse
from django.urls.base import reverse_lazy
from django.views.generic import (
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
    ListView,
    FormView,
)
from django.core.paginator import Paginator
from . import models, forms


class DeletePostView(DeleteView):

    model = models.Post
    template_name = "studios/post_confirm_delete.html"

    def get_success_url(self):
        pk = self.kwargs.get("studio_pk")
        return reverse("studios:posts", kwargs={"pk": pk})


class UpdatePostView(UpdateView):

    model = models.Post
    template_name = "studios/post_update.html"
    fields = (
        "title",
        "body",
    )

    def get_success_url(self):
        pk = self.kwargs.get("pk")
        studio_pk = self.kwargs.get("studio_pk")
        return reverse("studios:post-detail", kwargs={"pk": pk, "studio_pk": studio_pk})


class DetailPostView(DetailView):

    model = models.Post
    template_name = "studios/post_detail.html"


class AddPostView(FormView):

    form_class = forms.CreatePostForm
    template_name = "studios/post_create.html"

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        user = self.request.user
        form.save(pk, user)
        return redirect(reverse("studios:posts", kwargs={"pk": pk}))


def StudioPostsView(request, pk):
    page = request.GET.get("page")
    studio = models.Studio.objects.get(pk=pk)
    studio_posts = models.Post.objects.filter(studio=studio)
    paginator = Paginator(studio_posts, 10)
    posts = paginator.get_page(page)
    return render(
        request,
        "studios/studio_posts.html",
        {
            "pk": pk,
            "studio_posts": studio_posts,
            "studio": studio,
            "posts": posts,
        },
    )


class DeleteStudioView(DeleteView):

    model = models.Studio
    success_url = reverse_lazy("core:home")
    template_name = "studios/studio_confirm_delete.html"


class UpdateStudioView(UpdateView):

    model = models.Studio
    template_name = "studios/studio_update.html"

    fields = (
        "name",
        "desc",
        "image",
    )

    def get_success_url(self):
        pk = self.kwargs.get("pk")
        return reverse("studios:posts", kwargs={"pk": pk})


class DetailStudioView(DetailView):

    model = models.Studio
    template_name = "studios/studio_detail.html"
    context_object_name = "studio"


class CreateStudioView(FormView):

    template_name = "studios/studio_create.html"
    form_class = forms.CreateStudioForm

    def form_valid(self, form):
        studio = form.save()
        studio.host = self.request.user
        studio.save()
        return redirect(reverse("studios:posts", kwargs={"pk": studio.pk}))

users/views.py
import os
import requests
from django.http import request
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import FormView, DetailView
from django.urls import reverse_lazy
from django.urls.base import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordChangeView
from django.views.generic.edit import UpdateView
from django.core.files.base import ContentFile
from . import forms, models


class LoginView(FormView):

    template_name = "users/login.html"
    form_class = forms.LoginForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(
            self.request,
            username=email,
            password=password,
        )
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)


def log_out(request):
    logout(request)
    return redirect(reverse("core:home"))


class SignUpView(FormView):

    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        nickname = form.cleaned_data.get("nickname")
        password = form.cleaned_data.get("password")
        user = authenticate(
            self.request,
            email=email,
            nickname=nickname,
            username=email,
            password=password,
        )
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)


class UserProfileView(DetailView):

    model = models.User
    context_object_name = "user_obj"


class UpdateProfileView(UpdateView):

    model = models.User
    template_name = "users/update_profile.html"
    fields = (
        "first_name",
        "last_name",
        "avatar",
        "nickname",
        "bio",
        "gender",
        "birthdate",
        "phone",
        "language",
        "currency",
        "busker",
    )

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["first_name"].widget.attrs = {"placeholder": "이름"}
        form.fields["last_name"].widget.attrs = {"placeholder": "성"}
        form.fields["nickname"].widget.attrs = {"placeholder": "닉네임"}
        form.fields["bio"].widget.attrs = {"placeholder": "당신에 대해 알려주세요!"}
        form.fields["birthdate"].widget.attrs = {"placeholder": "생년월일 ex)2000-01-01"}
        form.fields["phone"].widget.attrs = {"placeholder": "연락처 ex)010-0000-0000"}
        return form

    def get_object(self, queryset=None):
        return self.request.user


class UpdatePassword(PasswordChangeView):

    template_name = "users/update_password.html"

    def get_success_url(self):
        return self.request.user.get_absolute_url()

templates/users/login.html
{% extends 'base.html' %}


{% block page_title %}Login{% endblock %}

{% block content %}
    <div class="container mx-auto mt-24 mb-48">
        <div class="box-border h-1/3 w-1/4 p-4 mb-10 border-4 mx-auto rounded-lg bg-white text-gray-700">
            <p class="text-xl text-center font-bold mb-3 mt-10">로그인</p>
            <p class="text-xs text-center mb-6">이용하기 위해 로그인해주세요</p>

            <form method="POST" action="{% url 'users:login' %}" class="text-gray-700 font-bold">
                {% csrf_token %}
                {{form.as_p}}
                <p class="text-red-500 text-xs italic mb-10 font-medium">If you do not have an ID, Please sign up.</p>
            <button class="bg-blue-500 hover:bg-blue-700 font-bold text-white w-24 min-w-full pt-2 pb-2 border border-blue-700 rounded" type="submit">로그인</button>
            </form>

            <a href="{% url 'users:signup' %}">
                <button class="bg-white hover:bg-blue-700 hover:text-white border-blue font-bold text-blue-700 w-24 min-w-full mt-4 pt-2 pb-2 border border-blue-700 rounded ">회원가입</button>    
            </a>
            
            {% include 'partials/social_login.html' %}
        </div>
    </div>
{% endblock %}

templates/users/my_page.html
{% extends 'base.html' %}

{% block page_title %}My Page{% endblock %}

{% block content %}

    <h1>my page</h1>
    <p>현재 로그인한 유저의 닉네임: {{user.nickname}}</p>

{% endblock %}

templates/users/signup.html
{% extends 'base.html' %}

{% block page_title %}Sign Up{% endblock %}

{% block content %}
    <div class="container mx-auto mt-24 mb-48">
        <div class="box-border h-1/3 w-1/4 p-4 mb-10 border-4 mx-auto rounded-lg bg-white text-gray-700">
            <p class="text-xl text-center font-bold my-10">회원가입</p>

            <form method="POST" action="{% url 'users:signup' %}" class="text-gray-700 font-bold">
                {% csrf_token %}
                {{form.as_p}}
            <button class="bg-blue-500 hover:bg-blue-700 font-bold text-white w-24 min-w-full pt-2 pb-2 border border-blue-700 rounded mt-5" type="submit">회원가입</button>
            </form>
            
            {% include 'partials/social_login.html' %}
        </div>
    </div>
{% endblock %}

templates/users/studio.html
{% extends 'base.html' %}

{% block page_title %}Studio{% endblock %}

{% block content %}

    <form method="POST" action="{% url 'users:login' %}">
        {% csrf_token %}
        {{form.as_p}}
        <button>Login</button>
    </form>

{% endblock %}

templates/users/update_password.html
{% extends 'base.html' %}

{% block page_title %}패스워드 변경{% endblock %}

{% block content %}

<div class="container w-4/5 mx-auto mt-16 mb-40 flex flex-row">
    {% include 'mixins/users/my_page_nav.html' %}

    <div class="flex flex-col w-4/5">
        <h1 class="font-bold text-2xl mb-10 text-yellow-400">패스워드 변경하기</h1>
        {% include 'mixins/auth/auth_form.html' with form=form cta="수정하기" %}
    </div>
</div>

{% endblock %}

templates/users/update_profile.html
{% extends 'base.html' %}

{% block page_title %}회원정보 수정{% endblock %}

{% block content %}

<div class="container w-4/5 mx-auto mt-16 mb-40 flex flex-row">
    {% include 'mixins/users/my_page_nav.html' %}

    <div class="flex flex-col w-4/5">
        <h1 class="font-bold text-2xl mb-10 text-yellow-400">프로필 수정하기</h1>
        {% include 'mixins/auth/auth_form.html' with form=form cta="수정하기" %}
    </div>
</div>

{% endblock %}

templates/users/user_detail.html
{% extends 'base.html' %}

{% block page_title %}{{user.username}}{% endblock %}

{% block content %}

<div class="container w-4/5 mx-auto mt-16 mb-64 flex flex-row">
    {% include 'mixins/users/my_page_nav.html' %}

    <div class="flex flex-col w-4/5">
        <div class="flex flex-row pb-36 h-50vh pt-12 px-12 bg-gray-900 rounded-lg relative">
            <div class="mr-10">
                {% include 'mixins/users/user_avatar.html' %}
            </div>
            <div class="w-full">
                <div class="flex flex-row items-center mb-3">
                    <div class="flex flex-row items-center">
                        {% if user.nickname %}
                            <span class="text-3xl mr-3 text-yellow-400">{{user_obj.nickname}}</span>
                        {% else %}
                            <span class="mr-3 text-yellow-400">닉네임을 추가해주세요</span>
                        {% endif %}
                        
                        {% if user_obj.busker %}
                            <span class="bg-indigo-600 py-1 px-3 text-sm rounded-xl">BUSKER</span>
                        {% endif %}
                    </div>
                </div>
                <span class="text-xl block mb-6 text-gray-200  border-b border-gray-400 pb-5">{{user_obj.email}}</span>
                <span class="text-xl block">{{user_obj.bio}}</span>
            </div>
            
            {% if user.is_authenticated %}
                <div class="absolute bottom-5 right-12">
                    <a href="{% url 'users:update' %}" class="bg-yellow-500 rounded-xl py-1 px-5 text-busker-navy font-bold mr-2">프로필 수정</a>
                    <a href="{% url 'users:password' %}" class="bg-yellow-500 rounded-xl py-1 px-5 text-busker-navy font-bold">패스워드 변경</a>
                </div>
            {% endif %}
            
        </div>
    </div>
</div>

{% endblock %}