config/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("broadcasts/", include("broadcasts.urls", namespace="broadcasts")),
    path("studios/", include("studios.urls", namespace="studios")),
    path("accounts/", include("allauth.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studios/urls.py
from django.urls import path
from . import views


app_name = "studios"

urlpatterns = [
    path("create/", views.CreateStudioView.as_view(), name="create"),
    path("<int:pk>/", views.DetailStudioView.as_view(), name="detail"),
    path("update/<int:pk>/", views.UpdateStudioView.as_view(), name="update"),
    path("delete/<int:pk>/", views.DeleteStudioView.as_view(), name="delete"),
    path("<int:pk>/posts/", views.StudioPostsView, name="posts"),
    path(
        "<int:pk>/posts/add",
        views.AddPostView.as_view(),
        name="add-posts",
    ),
    path(
        "<int:studio_pk>/posts/<int:pk>/",
        views.DetailPostView.as_view(),
        name="post-detail",
    ),
    path(
        "<int:studio_pk>/posts/<int:pk>/update",
        views.UpdatePostView.as_view(),
        name="post-update",
    ),
    path(
        "<int:studio_pk>/posts/<int:pk>/delete",
        views.DeletePostView.as_view(),
        name="post-delete",
    ),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update_profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update_password/", views.UpdatePassword.as_view(), name="password"),
]

studios/models.py
from typing import Tuple
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from core import models as core_models
import core
from users import models as user_models


class Category(core_models.TimeStampedModel):

    """Category Model Definition"""

    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Post(core_models.TimeStampedModel):

    """Post Model Definition"""

    class Meta:
        ordering = ["-created"]

    NOTICE = "NT"
    BULLETIN = "BL"
    BOARD_CHOICES = [
        (NOTICE, "공지사항"),
        (BULLETIN, "자유게시판"),
    ]

    title = models.CharField(max_length=200, null=True)
    writer = models.ForeignKey(
        user_models.User, related_name="posts", on_delete=models.CASCADE
    )
    body = RichTextUploadingField(null=True)
    studio = models.ForeignKey("Studio", related_name="posts", on_delete=models.CASCADE)
    category = models.CharField(
        max_length=40, null=True, choices=BOARD_CHOICES, default=BULLETIN
    )

    def __str__(self):
        return self.title[:30]


class Studio(core_models.TimeStampedModel):

    """Studio Model Definition"""

    name = models.CharField(max_length=160, blank=True, null=True)
    desc = models.TextField(blank=True, null=True)
    image = models.ImageField(
        upload_to="studio_images",
        blank=True,
        null=True,
        default="broadcast_images/no_image.png",
    )
    host = models.OneToOneField(
        user_models.User,
        related_name="studio",
        on_delete=models.CASCADE,
        primary_key=True,
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("studios:detail", kwargs={"pk": self.pk})

studios/forms.py
from django import forms
from django.forms import fields, widgets
from . import models


class CreatePostForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = (
            "title",
            "body",
        )

    def save(self, pk, user, *args, **kwargs):
        post = super().save(commit=False)
        studio = models.Studio.objects.get(pk=pk)
        post.studio = studio
        post.writer = user
        post.save()


class CreateStudioForm(forms.ModelForm):
    class Meta:
        model = models.Studio
        fields = (
            "name",
            "desc",
            "image",
        )

    def save(self, *args, **kwargs):
        studio = super().save(commit=False)
        return studio


class UpdateStudioForm(forms.Form):
    pass

studios/views.py
from django.forms import forms
from django.shortcuts import redirect, render
from django.urls import reverse
from django.urls.base import reverse_lazy
from django.views.generic import (
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
    ListView,
    FormView,
)
from django.core.paginator import Paginator
from . import models, forms


class DeletePostView(DeleteView):

    model = models.Post
    template_name = "studios/post_confirm_delete.html"

    def get_success_url(self):
        pk = self.kwargs.get("studio_pk")
        return reverse("studios:posts", kwargs={"pk": pk})


class UpdatePostView(UpdateView):

    model = models.Post
    template_name = "studios/post_update.html"
    fields = (
        "title",
        "body",
    )

    def get_success_url(self):
        pk = self.kwargs.get("pk")
        studio_pk = self.kwargs.get("studio_pk")
        return reverse("studios:post-detail", kwargs={"pk": pk, "studio_pk": studio_pk})


class DetailPostView(DetailView):

    model = models.Post
    template_name = "studios/post_detail.html"


class AddPostView(FormView):

    form_class = forms.CreatePostForm
    template_name = "studios/post_create.html"

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        user = self.request.user
        form.save(pk, user)
        return redirect(reverse("studios:posts", kwargs={"pk": pk}))


def StudioPostsView(request, pk):
    page = request.GET.get("page")
    studio = models.Studio.objects.get(pk=pk)
    studio_posts = models.Post.objects.filter(studio=studio)
    paginator = Paginator(studio_posts, 10)
    posts = paginator.get_page(page)
    return render(
        request,
        "studios/studio_posts.html",
        {
            "pk": pk,
            "studio_posts": studio_posts,
            "studio": studio,
            "posts": posts,
        },
    )


class DeleteStudioView(DeleteView):

    model = models.Studio
    success_url = reverse_lazy("core:home")
    template_name = "studios/studio_confirm_delete.html"


class UpdateStudioView(UpdateView):

    model = models.Studio
    template_name = "studios/studio_update.html"

    fields = (
        "name",
        "desc",
        "image",
    )

    def get_success_url(self):
        pk = self.kwargs.get("pk")
        return reverse("studios:posts", kwargs={"pk": pk})


class DetailStudioView(DetailView):

    model = models.Studio
    template_name = "studios/studio_detail.html"
    context_object_name = "studio"


class CreateStudioView(FormView):

    template_name = "studios/studio_create.html"
    form_class = forms.CreateStudioForm

    def form_valid(self, form):
        studio = form.save()
        studio.host = self.request.user
        studio.save()
        return redirect(reverse("studios:posts", kwargs={"pk": studio.pk}))

templates/studios/categories.html
{% extends 'base.html' %}

{% block page_title %}{{studio.host.nickname}}의 스튜디오{% endblock %}

{% block content %}

<div class="container  mx-auto w-4/5 mt-16 mb-64 flex flex-row">
    {% include 'mixins/studios/studio_nav.html' %}

    <div class=" w-4/5">
        <div class="w-full h-64 bg-cover bg-center mb-10 opacity-80" style="background-image: url({{studio.image.url}});"></div>
        <div class="flex justify-between mb-10">
            <span class="text-2xl">{{category.name}}</span>
            <a href="{% url 'studios:add-posts' pk=studio_pk %}" class="text-center bg-yellow-500 rounded-xl py-1 px-5 text-busker-navy font-bold mr-2 w-32">새 글쓰기</a>
        </div>
        <div>
            <table class="w-full mb-20">
                <thead class="h-12 bg-gray-900 mb-10">
                    <tr>
                        <th colspan="1" class="w-8 font-light text-gray-300">번호</th>
                        <th colspan="1" class="w-64 font-light text-gray-300">제목</th>
                        <th colspan="1" class="w-20 font-light text-gray-300">작성자</th>
                        <th colspan="1" class="w-20 font-light text-gray-300">작성일자</th>
                    </tr>
                </thead>
                <tbody>
                    {% for post in studio.posts.all %}
                        <tr class="h-16 border-b border-gray-500">
                            <td class="w-8 text-center font-light">{{post.pk}}</td>
                            <td class="w-64 text-left pl-10 font-light">
                                <a href="{% url 'studios:post-detail' studio_pk=studio.pk pk=post.pk %}">
                                    {{post.title}}
                                </a>
                            </td>
                            <td class="w-20 text-center font-light">{{post.writer.nickname}}</td>
                            <td class="w-20 text-center font-light">{{post.created|date:"D d M Y"}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        
        <div class="flex justify-end">
            {% if user == studio.host %}
                <a href="{% url 'studios:update' studio.pk %}" class="bg-yellow-500 rounded-xl py-1 px-5 text-busker-navy font-bold mr-2">스튜디오 수정 및 삭제</a>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

templates/studios/post_confirm_delete.html
{% extends "base.html" %}

{% block page_title %}게시글 삭제하기{% endblock page_title %}

{% block content %}
<div class="container w-4/5 mt-16 mb-40 mx-auto h-75vh">
    <form method="post" class=" bg-white w-full h-25vh p-12 rounded-md text-black">
        {% csrf_token %}
        <p class="text-xl mb-8 w-full">경고❗️ 정말로 "{{ object }}" 게시글을 삭제하시겠습니까?? 삭제하기 버튼을 누를 시, 해당 게시글에 관련된 모든 데이터가 삭제됩니다.</p>
        <input type="submit" value="삭제" class="block w-64 absolute bg-red-500 text-white border-none cursor-pointer">
    </form>
</div>

{% endblock %}

templates/studios/post_create.html
{% extends "base.html" %}

{% block page_title %}새 글쓰기{% endblock page_title %}

{% block content %}
<div class="container w-4/5 mt-16 mb-40 mx-auto">
    <div class="w-5/6 mx-auto">
        <h1 class="font-bold text-2xl mb-10 text-yellow-400">새 글쓰기</h1>
        <form action="#" method="POST" enctype="multipart/form-data" class="w-4/5">
            {% csrf_token %}
            {{form.media}}
            {{form.as_p}}
            <button type="submit" class="btn w-full">작성하기</button>
        </form>
    </div>
</div>
    
{% endblock %}

templates/studios/post_detail.html
{% extends 'base.html' %}

{% block page_title %}{{post.title}}{% endblock %}

{% block content %}

<div class="container w-4/5 mx-auto mt-16 mb-50vh flex flex-row">
    {% include 'mixins/studios/studio_nav.html' with studio=post.studio %}

    <div class="flex flex-col w-4/5">
        <div class="w-full h-56 bg-cover bg-center mb-10" style="background-image: url({{post.studio.image.url}});"></div>
        <div class="pt-10 px-10 rounded-lg bg-gray-900">
            <div class="text-3xl mb-3 text-yellow-400" >
                {{post.title}}
            </div>
            <div class="mb-3 flex justify-between">
                <span>{{post.writer.nickname}}</span>
                <span>{{post.created}}</span>
            </div>

            <div class="border-b border-gray-400">
            </div>
            
            <div class="mt-5 ">
                <p>{{post.body|safe}}</p>
            </div>

            <div class="flex justify-end mt-36 mb-10">
                <a href="{% url 'studios:posts' post.studio.pk %}" class="bg-blue-300 rounded-xl py-1 px-5 text-busker-navy font-bold mr-2 w-28 text-center">목록</a>
                {% if user == post.writer %}
                    <a href="{% url 'studios:post-update' studio_pk=post.studio.pk pk=post.pk %}" class="bg-yellow-500 rounded-xl py-1 px-5 text-busker-navy font-bold mr-2">게시글 수정</a>
                    <a href="{% url 'studios:post-delete' studio_pk=post.studio.pk pk=post.pk %}" class="bg-red-500 rounded-xl py-1 px-5 text-busker-navy font-bold mr-2">게시글 삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/studios/post_update.html
{% extends "base.html" %}

{% block page_title %}글 수정하기{% endblock page_title %}

{% block content %}
<div class="container w-4/5 mt-16 mb-40 mx-auto">
    <div class="w-5/6 mx-auto">
        <h1 class="font-bold text-2xl mb-10 text-yellow-400">글 수정하기</h1>
        <form action="{% url 'studios:post-update' studio_pk=post.studio.pk pk=post.pk %}" method="POST" enctype="multipart/form-data" class="w-4/5">
            {% csrf_token %}
            {{form.media}}
            {{form.as_p}}
        <button type="submit" class="btn w-full">수정하기</button>
    </form>
    </div>
</div>
    
{% endblock %}

templates/studios/studio_confirm_delete.html
{% extends "base.html" %}

{% block page_title %}스튜디오 생성하기{% endblock page_title %}

{% block content %}
<div class="container w-4/5 mt-16 mb-40 mx-auto h-75vh">
    <form method="post" class=" bg-white w-full h-25vh p-12 rounded-md text-black">
        {% csrf_token %}
        <p class="text-xl mb-8 w-full">경고❗️ 정말로 "{{ object }}" 스튜디오를 삭제하시겠습니까?? 삭제하기 버튼을 누를 시, 해당 스튜디오 관련 데이터가 모두 삭제됩니다.</p>
        <input type="submit" value="삭제" class="block w-64 absolute bg-red-500 text-white border-none cursor-pointer">
    </form>
</div>

{% endblock %}

templates/studios/studio_create.html
{% extends "base.html" %}

{% block page_title %}스튜디오 생성하기{% endblock page_title %}

{% block content %}
<div class="container w-4/5 mt-16 mb-40 mx-auto">
    <div class="w-4/5 mx-auto">
<<<<<<< HEAD
        <h1 class="font-bold text-2xl mb-10">스튜디오 생성</h1>
=======
        <h1 class="font-bold text-2xl mb-10 text-yellow-400">스튜디오 생성</h1>
>>>>>>> master
    <form action="{% url 'studios:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn w-full">스튜디오 만들기</button>
    </form>
    </div>
</div>
{% endblock %}

templates/studios/studio_posts.html
{% extends 'base.html' %}

{% block page_title %}{{studio.host.nickname}}의 스튜디오{% endblock %}

{% block content %}

<div class="container w-4/5 mx-auto mt-16 mb-50vh flex flex-row">
    {% include 'mixins/studios/studio_nav.html' %}

    <div class="flex flex-col w-4/5">
        <div class="w-full h-64 bg-cover bg-center mb-10 opacity-80 relative bg-gray-900" style="background-image: url({{studio.image.url}});">
            <span class="absolute top-1 right-2 text-sm font-bold">BUSKER</span>
        </div>
        <div class="flex justify-between mb-10">
            <span class="text-2xl">커뮤니티</span>
            <a href="{% url 'studios:add-posts' studio.pk %}" class="text-center bg-yellow-500 rounded-xl py-1 px-5 text-busker-navy font-bold mr-2 w-32">새 글쓰기</a>
        </div>
        <div>
            <table class="w-full mb-5">
                <thead class="h-12 bg-gray-900 mb-10">
                    <tr>
                        <th colspan="1" class="w-8 font-light text-gray-300">번호</th>
                        <th colspan="1" class="w-64 font-light text-gray-300">제목</th>
                        <th colspan="1" class="w-20 font-light text-gray-300">작성자</th>
                        <th colspan="1" class="w-20 font-light text-gray-300">작성일자</th>
                    </tr>
                </thead>
                <tbody>
                    {% for post in posts %}
                        <tr class="h-16 border-b border-gray-500">
                            <td class="w-8 text-center font-light">{{post.pk}}</td>
                            <td class="w-64 text-left pl-10 font-light">
                                <a href="{% url 'studios:post-detail' studio_pk=studio.pk pk=post.pk %}">
                                    {{post.title}}
                                </a>
                            </td>
                            <td class="w-20 text-center font-light">{{post.writer.nickname}}</td>
                            <td class="w-20 text-center font-light">{{post.created|date:"f a d M"}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

            <div class="w-full flex justify-center items-center text-lg relative">
                <span class="absolute right-0 text-sm pb-5 text-gray-300 ">{{posts.number}} 페이지</span>

                {% if posts.has_previous %}
                <a href="?page={{posts.previous_page_number}}" class="text-gray-300 mr-3 pl-2 py-2 text-2xl hover:text-yellow-400"><i class="fas fa-angle-double-left"></i></a>
                {% endif %}
    
                {% for p in posts.paginator.page_range %}
                    <a href="?page={{p}}" class="text-gray-300 mx-1 p-2 text-xl hover:text-yellow-400">{{p}}</a>
                {% endfor %}
                
                {% if posts.has_next %}
                    <a href="?page={{posts.next_page_number}}" class="text-gray-300 ml-3 pr-2 py-2 text-2xl hover:text-yellow-400"><i class="fas fa-angle-double-right"></i></a>
                {% endif %}
            </div>
        </div>
        
        <div class="flex justify-end">
            {% if user == studio.host %}
                <a href="{% url 'studios:update' studio.pk %}" class="bg-yellow-500 rounded-xl py-1 px-5 text-busker-navy font-bold mr-2">스튜디오 수정 및 삭제</a>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

templates/studios/studio_update.html
{% extends "base.html" %}

{% block page_title %}스튜디오 수정 및 삭제{% endblock page_title %}

{% block content %}
<div class="container w-4/5 mt-16 mb-40 mx-auto">
    <div class="w-4/5 mx-auto">
        <h1 class="font-bold text-2xl mb-10 text-yellow-400">스튜디오 수정</h1>
    <form action="{% url 'studios:update' studio.pk %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn w-full">스튜디오 수정하기</button>
    </form>

    <a href="{% url 'studios:delete' studio.pk %}" class="text-center block btn bg-red-500 text-gray-100">스튜디오 삭제하기</a>
    </div>
</div>
    

{% endblock %}